### ISSUE TITLE
Is it possibe to access request parameters in decorators?

### ISSUE THREAD

**Issue by mdbergmann** [mmontone/easy-routes#11]
Hi.
This is more a question.
I'd like to move parameter validation to a decorator, where the decorator function must have access to the already parsed parameters.
Is this possible? I couldn't find out.

**Comment by mmontone** [comment]
Hi. Unfortunately no. The handling of parameters is expanded into the defroute body. It could be made possible if I refactor the code that expands the parameter handling, turn it into a function and make it available. But that's not the case at the moment. 

It is still possible for you to handle parameters in a decorator by accessing hunchentoot request directly, but not path parameters.

**Comment by mdbergmann** [comment]
OK, no problem. Thanks.
