### ISSUE TITLE
Support for headers(-in) and cookies(-in) parameters

### ISSUE THREAD

**Issue by kilianmh** [mmontone/easy-routes#16]
Its great that we can access `&get`, `&post`, and `&path` parameters. 

Would the same be possible for `&header`, `&cookie` parameters?

**Comment by mmontone** [comment]
Ok. Should be possible. I'll have a look.

**Comment by mmontone** [comment]
I prefer keeping syntax for path and query parameters only. For header and cookies let's use Hunchentoot.
