### ISSUE TITLE
Support for PUT and DELETE method?

### ISSUE THREAD

**Issue by singy15** [mmontone/easy-routes#2]
README.md describes :method accepts either :get or :post.
Can I create routes for PUT or DELETE method?

It seems defroute method accepts :put or :delete and properly work.

**Comment by mmontone** [comment]
I think so. Put and delete are not dispatching properly?

**Comment by mmontone** [comment]
Ah. You mean PUT and DELETE are not mentioned in docs. I should probably revise that.

**Comment by singy15** [comment]
That's right, I mentioned about docs.

It's better than before.
Thanks for your effort and your great product.
