### ISSUE TITLE
Placeholder for route name? (don't know how to dump ROUTES:WILDCARD-TEMPLATE)

### ISSUE THREAD

**Issue by vindarel** [mmontone/easy-routes#3]
Hello (again),

We define routes like this:

    (easy-routes:defroute card-page ("/livre/:card" :method :get) ()

I tried to put the string name into a variable, in the hope to translate url names:

    (defvar *card-url-name* "/livre/:card")
    (easy-routes:defroute card-page (*card-url-name* :method :get) ()

but compiling it fails with:

```
Execution of a form compiled with errors.
Form:
  (LET ((EASY-ROUTES::%ROUTE
       (MAKE-INSTANCE 'EASY-ROUTES:ROUTE :SYMBOL 'CARD-PAGE :TEMPLATE
                      '(#<ROUTES:WILDCARD-TEMPLATE {10025DDBB3}>) :VARIABLES
                      '(:CARD-URL-NAME*) :REQUIRED-METHOD ':GET ...)))
  (SETF (GETHASH 'CARD-PAGE EASY-ROUTES::*ROUTES*) EASY-ROUTES::%ROUTE)
  (EASY-ROUTES::CONNECT-ROUTES)
  (DEFUN CARD-PAGE (CARD-URL-NAME*)
    (LET ()
      (DJULA:RENDER-TEMPLATE* +CARD-PAGE.HTML+ NIL :CARD CARD))))
Compile-time error:
  don't know how to dump #<ROUTES:WILDCARD-TEMPLATE {10025DDBB3}> (default MAKE-LOAD-FORM method called).
```

A quick try:

```
(routes:parse-template *card-url-name*)
("livre" #<ROUTES:VARIABLE-TEMPLATE {100228CEF3}>)
```

Any hints (in doing this, or translating urls)? thanks!

**Comment by mmontone** [comment]
Don't have much time right now for this.

I would consider subclassing the easy-routes-acceptor and implement the custom routing.

Other pointer: have a look at make-load-form and define for routes:wildcard-template.

This is the one for variable templates:
```
(defmethod make-load-form ((var routes:variable-template) &optional env)
  (declare (ignorable env))
  `(routes::make-variable-template ',(routes::template-data var)))
```

**Comment by vindarel** [comment]
OK, thanks for the pointers.

**Comment by mmontone** [comment]
Mmm. Not sure wildcard-templates is what you want. I don't remember this stuff very well to tell right now.

Another pointer?

Add url prefix at read time?

```lisp
(defvar *card-url-name* "/livre/:card")
(easy-routes:defroute card-page (#.*card-url-name* :method :get) ()
```

you may need to define *card-url-name* in a separate file for that, and load before the file with the routes is loaded.

**Comment by vindarel** [comment]
> Add url prefix at read time?

Yes! That works beautifully, thank you.
(I have yet to test the load order. It worked on the REPL)

Shall we close this (I'll add a line in the README), or shall we define a proper method?

**Comment by mmontone** [comment]
I don't understand exactly what you are trying to achieve with this, so, I don't know.

Why do this?

```
(defvar *card-url-name* "/livre/:card")
(easy-routes:defroute card-page (*card-url-name* :method :get) ()
```

**Comment by vindarel** [comment]
Because I wanted to be able to translate URLs, in order to have them in the user's mother tongue. If I deploy the app for a french person: the URL will be "/livre/…", but someone else who deploys my app in Argentina would prefer his users to see "/libro/…".
