### ISSUE TITLE
Example code wrong?

### ISSUE THREAD

**Issue by smtlaissezfaire** [mmontone/easy-routes#4]
I'm new to lisp so bear with me, but isn't this example code wrong?

```
(easy-routes:defroute name ("/foo/:x") (y &get z)
    (format nil "x: ~a y: ~y z: ~a" x y z))
```

I get the following with sbcl:

```
; in: EASY-ROUTES:DEFROUTE NAME
;     (FORMAT NIL "x: ~a y: ~y z: ~a" X Y Z)
; 
; caught ERROR:
;   during macroexpansion of (FORMATTER "x: ~a y: ~y z: ~a"). Use
;   *BREAK-ON-SIGNALS* to intercept.
;   
;    error in FORMAT: Unknown directive (character: LATIN_CAPITAL_LETTER_Y)
;     x: ~a y: ~y z: ~a
;               ^
; 
; compilation unit finished
;   caught 1 ERROR condition
```

Shouldn't it be?

```
(easy-routes:defroute name ("/foo/:x") (y &get z)
    (format nil "x: ~a y: ~a z: ~a" x y z))
```

Once again, sorry if this is a newb question.

**Comment by PuercoPop** [comment]
@smtlaissezfaire Your suggestion is the same, but you are right that the example code is wrong. Replace the `~y` for `~A` in the example and it should work `(format nil "x: ~a y: ~a z: ~a" x y z)`.

**Comment by smtlaissezfaire** [comment]
Thanks @PuercoPop ! Meant to submit a patch but didn't get around to it. 

Thanks again for the quick response time!
