### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mmontone/easy-routes#6]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id 65a75ac4c4c7ccdd4bfe30a1a45714b48bbc51a4

*easy-routes+errors* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A50103}>: Component :HUNCHENTOOT-ERRORS not found, required by #<SYSTEM "easy-routes+errors">

```

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/easy-routes.html)

**Comment by mmontone** [comment]
Ah. We need to include hunchentoot-errors in quicklisp.

**Comment by mmontone** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/1914
