### ISSUE TITLE
Allow for variables as a path for the routes

### ISSUE THREAD

**Issue by alejandrogallo** [mmontone/easy-routes#9]
I went ahead and created a patch, you can consider adding it, I think
this makes sense

```diff
diff -u --label /home/gallo/quicklisp/dists/quicklisp/software/easy-routes-20220707-git/easy-routes.lisp --label \#\<buffer\ easy-routes.lisp\> /home/gallo/quicklisp/dists/quicklisp/software/easy-routes-20220707-git/easy-routes.lisp /tmp/buffer-content-nm8tpn
--- /home/gallo/quicklisp/dists/quicklisp/software/easy-routes-20220707-git/easy-routes.lisp
+++ #<buffer easy-routes.lisp>
@@ -167,7 +167,8 @@
 
 with:
 
-* path: A string with an url path that can contain arguments prefixed with a colon.
+* path: A string or a symbol evaluating to a string with an url path
+  that can contain arguments prefixed with a colon.
   Like \"/foo/:x/:y\", where :x and :y are bound into x and y variables in the context of the route body.
 * route-options: possible options are
      * :method - The HTTP method to dispatch, as a keyword. Default is :get.
@@ -198,9 +199,12 @@
             &path (x 'integer))
                   (format nil \"~A\" (+ x y)))"
 
-  (let* ((template (if (listp template-and-options)
-                       (first template-and-options)
-                       template-and-options))
+  (let* ((template (let ((template (if (listp template-and-options)
+                                       (first template-and-options)
+                                       template-and-options)))
+                     (etypecase template
+                       (string template)
+                       (symbol (eval template)))))
          (variables (routes:template-variables
                      (routes:parse-template template)))
          (arglist (mapcar (alexandria:compose #'intern #'symbol-name)

Diff finished.  Tue Aug 15 17:18:41 2023
```

**Comment by mmontone** [comment]
Ok. What do you need this for? More flexibility in the routes? You have an example?

I would also consider using `(funcall (symbol-function template))` instead of eval.

**Comment by alejandrogallo** [comment]
Sorry for not explaining


I have something like

```lisp
(defvar *home-path* "/pflanzis/home")

(easy-routes:defroute index (*home-path*
                             :decorators (@login))
    (q)
    ....)
```


How do you do this normally?
Like this it does not work because the function to trim
the path does an implicit conversion with `symbol-name`,
i.ep

```lisp
(string-left-trim "/" '*lalala*) ;; => "*LALALA*"
```

**Comment by mmontone** [comment]
Ok. I think your use case makes sense. I'll think about it a bit and
integrate later today. Thanks.

**Comment by alejandrogallo** [comment]
gracias a ti!

**Comment by mmontone** [comment]
This is a related issue: https://github.com/mmontone/easy-routes/issues/3

**Comment by mmontone** [comment]
This was accepted as a solution, but I'm not sure it applies in your case: https://github.com/mmontone/easy-routes/issues/3#issuecomment-626792181

Do you have an opinion?

**Comment by mmontone** [comment]
It uses a read-time "trick". So perhaps a patch like yours is better, but I'm not sure.

**Comment by alejandrogallo** [comment]
ah, yes with the reader.
That works actually, because the important thing is to have
somewhere the paths parametrized.

I agree that evaling is not maybe the best thing,
I tried with a symbol-macro but it did not work,
but I guess the reader is fair enough, maybe
one can add a comment in the defroute docstring
for future reference.

**Comment by mmontone** [comment]
> I tried with a symbol-macro but it did not work,

It may work with symbol-value. I'll try.

**Comment by mmontone** [comment]
@alejandrogallo  Pushed a slightly different version of your patch. Please close the issue if you think it is correct.

**Comment by alejandrogallo** [comment]
oh yes, this looks completely fine! Thank you very much for the quick fix!
